version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sh -c "python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:alpine
    ports:
      - 8010:80
    volumes:
      - ./configs/dev/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./configs/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/www/data/staticfiles
      - ./media:/www/data/media
    depends_on:
      - web