version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sh -c "python3 manage.py collectstatic --noinput && python3 manage.py compilemessages && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn -c ./configs/gunicorn/conf.py unamazoo.wsgi"
    deploy:
      replicas: 2

  nginx:
    image: nginx:alpine
    ports:
      - 8011:80
#      - 443:443
    volumes:
#      - ./configs/certbot.sh:/app/configs/certbot.sh
#      - ./configs/letsencrypt:/etc/letsencrypt
      - ./configs/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/www/data/staticfiles
      - ./media:/www/data/media
    depends_on:
      - web
#    command: sh -c "/app/configs/certbot.sh && nginx -g 'daemon off;'"