# Generated by Django 5.0 on 2024-04-09 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('name_pt_br', models.CharField(max_length=60, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='Nome')),
                ('scientific_name', models.CharField(max_length=70, verbose_name='Nome científico')),
                ('type', models.CharField(choices=[('Anfíbio', 'Anfíbio'), ('Ave', 'Ave'), ('Mamífero', 'Mamífero'), ('Peixe', 'Peixe'), ('Réptil', 'Réptil')], default='mamífero', max_length=20, verbose_name='Tipo')),
                ('lifetime', models.PositiveSmallIntegerField(default=0, verbose_name='Tempo de vida')),
                ('diet', models.CharField(choices=[('Carnívoro', 'Carnívoro'), ('Carnívoro', 'Carnívoro'), ('Detritívoro', 'Detritívoro'), ('Frugívoro', 'Frugívoro'), ('Herbívoro', 'Herbívoro'), ('Insetívoro', 'Insetívoro'), ('Invertívoro', 'Invertívoro'), ('Onívoro', 'Onívoro'), ('Perifitívoro', 'Perifitívoro'), ('Frugívoro', 'Frugívoro'), ('Herbívoro', 'Herbívoro'), ('Insetívoro', 'Insetívoro'), ('Invertívoro', 'Invertívoro'), ('Onívoro', 'Onívoro'), ('Perifitívoro', 'Perifitívoro')], default='herbivoro', max_length=20, verbose_name='Dieta')),
                ('weight', models.FloatField(default=0, verbose_name='Peso')),
                ('weight_measure', models.CharField(choices=[('kg', 'kg'), ('g', 'g')], default='kg', max_length=2, verbose_name='Unidade de Medida do Peso')),
                ('status', models.CharField(choices=[('Sem riscos', 'Sem riscos'), ('Vulnerável', 'Vulnerável'), ('Pouco preocupante', 'Pouco preocupante')], default='semriscos', max_length=20, verbose_name='Status de Risco')),
                ('adoption_link', models.URLField(default='http://pag.ae/7ZyUJfPM3', verbose_name='Link para apoio')),
                ('main_image', models.ImageField(upload_to='animais', verbose_name='Imagem Principal')),
                ('secondary_image', models.ImageField(upload_to='animais', verbose_name='Imagem Secundária')),
                ('video', models.CharField(default='videos/zoo-unama.mp4', max_length=200, verbose_name='Vídeo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('title_pt_br', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('description_pt_br', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('year', models.PositiveSmallIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2099)], verbose_name='Ano')),
                ('semester', models.CharField(choices=[('1', '1°'), ('2', '2°')], default='1', max_length=1, verbose_name='Semestre')),
                ('file', models.FileField(upload_to='editais', verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('description_pt_br', models.TextField(max_length=2000, null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(max_length=2000, null=True, verbose_name='Descrição')),
                ('place', models.CharField(choices=[('bannermain', 'Banner Principal'), ('infosuperior', 'Informações da Indigenazinha'), ('aboutproject', 'Sobre o Projeto'), ('zooarea', 'Área do Zoológico'), ('zoospecies', 'Espécies do Zoológico'), ('livezoo', 'Live Zoo'), ('testimonials', 'Depoimentos'), ('related_work', 'Trabalhos Relacionados'), ('donations', 'Doações'), ('food_donation', 'Doação de Alimentos'), ('adopt', 'Adote'), ('exchange', 'Intercâmbio'), ('exchange_reg', 'Inscrição de Intercâmbio'), ('institutional_pages', 'Páginas Institucionais')], default='testimonials', max_length=20, verbose_name='Onde isso vai aparecer?')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('video', models.FileField(blank=True, null=True, upload_to='postagem', verbose_name='Vídeo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('title_pt_br', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('subtitle_pt_br', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtítulo')),
                ('subtitle_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtítulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='postagem', verbose_name='Imagem')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainsite.post')),
            ],
            options={
                'verbose_name': 'Imagem do Post',
                'verbose_name_plural': 'Imagens do Post',
            },
        ),
    ]
