# Generated by Django 5.0 on 2024-06-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Descrição'),
        ),
    ]
