# Generated by Django 5.0 on 2025-02-21 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_animal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='year',
            field=models.PositiveSmallIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2099)], verbose_name='Ano'),
        ),
    ]
